apiVersion: v2
appVersion: 2.11.2
description: A Helm chart for multicluster-engine - CRDs
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine-crds
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:99716be167f01245cf8793490ac9ccd0108de6d6f3c1fc3947e8f680f5b00cc3
type: application
version: 2.11.2
